services:
  ffmpeg:
    image: linuxserver/ffmpeg:8.1.2
    entrypoint: ["ffmpeg"]
    network_mode: "host"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  rdm-vision:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - ffmpeg
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json:ro
      - ./models:/app/models:ro
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"